[package]
name = "distributed-topic-tracker-exp"
version = "0.1.0"
edition = "2024"

[dependencies]
secp256k1 = { version = "0.31.1", features = ["rand", "hashes"] }
sha2 = "0.10"
anyhow = "1"
z32 = "1.3.0"